version: '3.8'

services:
  node-advance:
    container_name: node-advance
    image: node
    ports:
      - 3000:3000
    env_file:
      - .env
    build:
      context: .
    depends_on:
      postgres_db:
        condition: service_started

  postgres_db:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    #     volumes:
    #       - pgdata:/var/lib/postgresql/data

    # volumes:
    #   pgdata:
