version: "3.8"

services:
  node_advance:
    image: node_advance
    container_name: node_advance
    ports:
      - "3000:3000"
    env_file:
      - .env
    build:
      context: .
    depends_on:
      postgres_db:
        condition: service_started

  postgres_db:
    container_name: postgres_db
    hostname: postgres_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "mydb"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
